config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated(:user) do
    root to: "fridge_lists#show", as: :authenticated_root
  end
  root to: "pages#home"

  resources :fridge_lists, only: [ :show ] do
   resources :fridge_list_ingredients, only: [:create]
  end

  resources :recipes, only: [ :index ] do
    resources :reviews, only: [:create]
  end

  resources :ingredients, only: [:destroy]
  resources :reviews, only: [:destroy]
  resources :fridge_list_ingredients, only: [:destroy]




  get "recipes/:recipe_id/like_rails", to: "recipes#like_rails", as: :like
  get "recipes/:recipe_id/unlike_rails", to: "recipes#unlike_rails", as: :unlike
  get "recipes/:recipe_id/mark", to: "recipes#mark", as: :mark
  get "recipes/:recipe_id/mark_undone", to: "recipes#mark_undone", as: :unmark
  get "recipes/all_done_recipes", to: "recipes#all_done_recipes", as: :all_done
  get "favorites", to: "recipes#all_favorite_recipes", as: :favorites
  post '/recipes', to: 'recipes#index', as: 'search_recipes'


end

app/models/fridge_list.rb
class FridgeList < ApplicationRecord
  has_many :fridge_list_ingredients
  has_many :ingredients, through: :fridge_list_ingredients, dependent: :destroy
  belongs_to :user
end

app/controllers/fridge_list_controller.rb
class FridgeListController < ApplicationController
  before_action :set_fridge_list, only: [:edit, :update, :destroy]

  def index
    @fridge_list = FridgeList.all
    @ingredient = Ingredient.all
    @user = User.all
  end

  def new
    @fridge_list = FridgeList.new
  end

  def create
    @fridge_list = FridgeList.new(fridge_list_params)

    if @fridge_list.save
      redirect_to @fridge_list
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @fridge_list.update(fridge_list_params)
      redirect_to @fridge_list
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @fridge_list.destroy

    redirect_to fridge_lists_url
  end

  private

  def set_fridge_list
    @fridge_list = FridgeList.find(params[:id])
  end

end

app/controllers/fridge_lists_controller.rb
class FridgeListsController < ApplicationController
  def show
    @fridge_list = FridgeList.find_by(user_id: current_user)
    # @fridge_list = current_user.fridge_list
    puts "Current User: #{current_user.inspect}"
    @categories = Category.all
    @fridge_list_ingredient = @fridge_list.fridge_list_ingredients.find_by(params[:fridge_list_ingredients])
    @fridge_list_ingredients = FridgeListIngredient.new
  end
end

app/views/fridge_lists/show.html.erb
<div class="background-image"></div>
<div class="container-show pb-2 pb-md-0">
  <div class="fridge-show">
    <h6>Hello <%= current_user.username %>,</h6>
    <p>Welcome to your fridge.🍽</p>
    <% @categories.each do |category| %>
      <button type="button" class="btn btn-category" data-bs-toggle="modal" data-bs-target="#staticBackdrop<%= category.id %>"
        style="display: block; margin-bottom: 20px; margin-left: -15px;">
        <h3>＋<%= category.name %></h3>
      </button>
      <div class="saved_ingredients" data-controller="delete-ingredients">
        <ul>
          <% @fridge_list.fridge_list_ingredients.each do |list_ingredient| %>
            <% if list_ingredient.ingredient.category_id == category.id %>
              <li>
                <div class="d-flex button-delete">
                  <div class="ingredient-name">
                    <%= list_ingredient.ingredient.name %>
                  </div>
                  <div class="delete-link">
                    <%= link_to fridge_list_ingredient_path(list_ingredient), class: "text-decoration-none", data: { turbo_method: :delete } do %>
                      x
                    <% end %>
                  </div>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <%# raise %>
    <% end %>

      <!-- Modal -->
      <%# Create Fridge_List Ingredients %>
    <% @categories.each do |category| %>
        <div class="modal fade" id="staticBackdrop<%= category.id %>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title"><%= category.name %> <i class="fa-solid fa-utensils" style="color: #000000;"></i></h4>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <%= simple_form_for [@fridge_list, @fridge_list_ingredients] do |f| %>
                      <div class="ingredient-checkboxes">
                        <% category.ingredients.each do |ingredient| %>
                          <div class="tag-item">
                            <%= f.association :ingredient,
                                            as: :check_boxes,
                                            value_method: :id,
                                            collection: [ingredient],
                                            include_hidden: false,
                                            checked: false,
                                            input_html: { class: "tag-selector", value: ingredient.name, id: "checkbox_#{ingredient.id}" },
                                            item_wrapper_class: 'tag-item' %>
                            <%#= f.hidden_field :ingredient_id, value: ingredient.id %>
                          </div>
                        <% end %>
                      </div>
                      <div class="modal-footer">
                          <%# <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> %>
                          <%= f.submit "Add to fridge", class: "btn btn-primary" %>
                      </div>
                    <% end %>
                </div>
              </div>
            </div>
        </div>
    <% end %>
    <a class="btn btn-get-recipes mb-5 mb-md-0", href="<%= recipes_path(fridge_list_ingredient: { selected_ingredient: @fridge_list.ingredients.pluck(:name) }) %>">Get Recipes</a>
  </div>
</div>