config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated(:user) do
    root to: "fridge_lists#show", as: :authenticated_root
  end
  root to: "pages#home"

  resources :fridge_lists, only: [ :show ] do
   resources :fridge_list_ingredients, only: [:create]
  end

  resources :recipes, only: [ :index ] do
    resources :reviews, only: [:create]
  end

  resources :ingredients, only: [:destroy]
  resources :reviews, only: [:destroy]
  resources :fridge_list_ingredients, only: [:destroy]




  get "recipes/:recipe_id/like_rails", to: "recipes#like_rails", as: :like
  get "recipes/:recipe_id/unlike_rails", to: "recipes#unlike_rails", as: :unlike
  get "recipes/:recipe_id/mark", to: "recipes#mark", as: :mark
  get "recipes/:recipe_id/mark_undone", to: "recipes#mark_undone", as: :unmark
  get "recipes/all_done_recipes", to: "recipes#all_done_recipes", as: :all_done
  get "favorites", to: "recipes#all_favorite_recipes", as: :favorites
  post '/recipes', to: 'recipes#index', as: 'search_recipes'


end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, :description, :instruction, :preparation_time, presence: true
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
  belongs_to :user
  acts_as_favoritable

  include PgSearch::Model
  pg_search_scope :search_by_ingredients,
      against: [ :description, :instruction ],
      using: {
        tsearch: {
          prefix: true,
          any_word: true
        } # <-- now `superman batm` will return something!
      }

  pg_search_scope :search_by_recipe_name,
      against: [ :name, :description, :instruction ],
      using: {
        tsearch: {
          prefix: true,
          any_word: true
        }
      }
end

app/controllers/recipes_controller.rb
require "open-uri"
class RecipesController < ApplicationController

  def index
    @recipes = []
    @api = RecipeApi.new(ENV["APP_SPOON_KEY"])
    if params[:fridge_list_ingredient].present?
      # current_user.recipes.destroy_all//Kathy
      # @recipes = Recipe.search_by_ingredients(search_params[:selected_ingredient])/marina
      ingredients = params[:fridge_list_ingredient][:selected_ingredient].join(",")
      @api_recipes = @api.recipe_by_ingredient(ingredients)
      recipes_id = @api_recipes["results"].map { |hash| hash["id"] }
      recipes_id.each do |api_id|
#skip recipes if they already exist in the DB with the same id from the api
        @recipe = Recipe.find_by(api_id: api_id)
#
#add a recipe to @recipes if
        if @recipe.present?
          @recipes << @recipe
          next
        end
        #
        @api_recipe = @api.recipe_information(api_id)
        if @api_recipe["image"].present?
          recipe = Recipe.new(
            "api_id"=>api_id,
            "name"=> @api_recipe["title"],
            "preparation_time"=> @api_recipe["readyInMinutes"],
            "number_of_portions"=> @api_recipe["servings"],
            "instruction"=> @api_recipe["instructions"],
            "description"=> @api_recipe["summary"]
          )
          file = URI.open(@api_recipe["image"])
          recipe.photo.attach(io: file, filename: "recipe.png", content_type: "image/png")
          recipe.user = current_user
          if recipe.save
            @recipes << recipe
          end
        end
      end
    end
  end

  def create_recipe_from_api

  end

  def like_rails
    recipe = Recipe.find(params[:recipe_id])
    current_user.favorite(recipe)
    head :ok
  end

  def unlike_rails
    recipe = Recipe.find(params[:recipe_id])
    current_user.unfavorite(recipe)
    head :ok
  end

  def all_favorite_recipes
    @all_favorites = current_user.all_favorites
    @favorite_recipes = []
    @all_favorites.each do |favorite|
      @favorite_recipes << favorite.favoritable_id
    end
    @favorite_recipes = Recipe.where(id: @favorite_recipes)
    if params[:query].present?
      @favorite_recipes = @favorite_recipes.search_by_recipe_name(params[:query])
    else
      @all_favorites = current_user.all_favorites
    end
  end

  def mark
    recipe = Recipe.find(params[:recipe_id])
    recipe.done = true
    recipe.save!
    # redirect_to recipes_path
    head :ok
  end

  def mark_undone
    recipe = Recipe.find(params[:recipe_id])
    recipe.done = false
    recipe.save!
    # redirect_to recipes_path
    head :ok
  end

  def all_done_recipes
    # @done_recipes = Recipe.select { |recipe| recipe[:done] == true }
    # @done_recipes = Recipe.where(done: true) this would be for all the saved ones
    @done_recipes = Recipe.where(done: true)
  end

  private
  def search_params
    params.require(:fridge_list_ingredient).permit(selected_ingredient: [])
  end
end

app/views/recipes/all_done_recipes.html.erb
<div>
  <div class="text-center" >
    <h1 class="color-yellow-bk"> You've saved these recipes:</h1>
  </div>
  <div class="my-4 mx-4">
    <% if @done_recipes.empty? %>
      <h2>Recipe not found</h2>
    <% else %>
      <% @done_recipes.each do |recipe| %>
        <div  data-controller="favoritable"  data-favoritable-mark-path-value="<%= mark_path(recipe.id) %>"  data-favoritable-unmark-path-value="<%= unmark_path(recipe.id) %>" data-favoritable-like-path-value="<%= like_path(recipe.id) %>" data-favoritable-unlike-path-value="<%= unlike_path(recipe.id) %>">
          <div class="card-whole-saved mt-3">
            <div class="position-relative">
              <div class="col-md-4" data-bs-toggle="modal" data-bs-target="#exampleModal<%= recipe.id %>">
                <%= cl_image_tag recipe.photo.key, class:"d-block actual-pic ", alt:"Poster", crop: :fill, style:" width: 100%; height: 170px;object-fit: cover;"  %>
              </div>
              <div class="position-absolute top-0 start-0 p-2">
                <i class="fas fa-info-circle"></i>
              </div>
            </div>
            <div class="card-body">
              <h5 class="mx-2 my-2 name-recipe"><%= recipe.name.capitalize%></h5>
              <div class="mx-2 d-flex justify-content-end">
                <p class="p-icon-fav "><i class="mx-2 pe-2 fa-solid fa-user-group iconico ">   <%= recipe.number_of_portions%></i></p>
                <p class="p-icon-fav "><i class=" fa-regular fa-clock iconico ">   <%= recipe.preparation_time%></i>m</p>
              </div>
              <div class="d-flex" >
                <div class="cardib">
                  <p class="cardib-text"><%= raw recipe.description.first(180)%>...</p>
                </div>
              </div>
            </div>
            <div class="mx-2 d-flex justify-content-end align-items-end">
              <i class="fa-regular fa-circle-check icon-index px-1 <%= 'd-none' if recipe.done? %>" <%= recipe.id %> style="color: gray " data-favoritable-target="markasdone"  data-action="click->favoritable#mark_js" ></i>
              <i class="fa-regular fa-circle-check icon-index px-1 <%= 'd-none' unless recipe.done? %>" <%= recipe.id %> style="color: green" data-favoritable-target="markedasdone"  data-action="click->favoritable#unmark_js" ></i>
              <i class="fa-solid fa-heart icon-index  <%= 'd-none' unless recipe.favorited_by?(current_user) %>"  data-favoritable-target="liked" style="color: #ff2600;" data-action="click->favoritable#unlike_js"></i>
              <i class="fa-regular fa-heart icon-index  <%= 'd-none' if recipe.favorited_by?(current_user) %>" data-favoritable-target="unliked"  style="color: #ff2600;" data-action="click->favoritable#like_js"></i>
            </div>
          </div>
          <!-- Modal -->
          <div class="modal fade"  id="exampleModal<%= recipe.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" style="top: -45px;">
            <div class="modal-dialog modal-dialog-centered sizing">
              <div class="modal-content radius-card " style="border-bottom-left-radius: 77px; border-bottom-right-radius: 70px;">
                <div class="modal-header modal-img-card">
                  <div class="heartt-arrow">
                    <i class=" ml-10 fa-solid fa-circle-left" style="color: #ffd672" data-bs-dismiss="modal"></i>
                    <i class="fa-regular fa-heart icon-index  <%= 'd-none' if recipe.favorited_by?(current_user) %>" data-favoritable-target="unliked"  style="color: #ff2600; margin-left: 338px;" data-action="click->favoritable#like_js"></i>
                    <i class="fa-solid fa-heart icon-index  <%= 'd-none' unless recipe.favorited_by?(current_user) %>"  data-favoritable-target="liked" style="color: #ff2600; margin-left: 338px;" data-action="click->favoritable#unlike_js"></i>
                  </div>
                  <div class="background-banner">
                    <%= cl_image_tag recipe.photo.key, class:"actual-pic modal-pic ", alt:"Banner", crop: :fill  %>
                  </div>
                </div>
                <div class="card card-modal">
                    <div class="modal-body ">
                      <h1 class="modal-title bold-title" id="exampleModalLabel" style="color: black"><%= recipe.name.capitalize%></h1>
                      <hr style="color: black">
                      <div class="instructions">
                        <div class="cardi-instruction" style="color: black"><%= raw recipe.instruction %></div>
                      </div>
                    </div>
                  <div class="d-flex justify-content-space-between mt-3"  >
                    <div class="d-flex" >
                      <div class=" justify-content-center icons-clock">
                        <p><i class=" fa-solid fa-user-group " style="color:black" ><%= recipe.number_of_portions%></i></p>
                        <p><i class=" fa-regular fa-clock" style="color:black" ><%= recipe.preparation_time %></i></p>
                      </div>
                    </div>
                    <div class="done">
                      <i class="fa-regular fa-circle-check icon-index px-1 <%= 'd-none' if recipe.done? %>" <%= recipe.id %> style="color: gray " data-favoritable-target="markasdone"  data-action="click->favoritable#mark_js" ></i>
                      <i class="fa-regular fa-circle-check icon-index px-1 <%= 'd-none' unless recipe.done? %>" <%= recipe.id %> style="color: green" data-favoritable-target="markedasdone"  data-action="click->favoritable#unmark_js" ></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipes/all_favorite_recipes.html.erb
  <div>
    <div class="text-center" >
      <h1 class="color-purple-bk"> Your favorite recipes:</h1>
    </div>
    <div data-controller='virtual-keyboard' class="search">
      <div class="row justify-content-center">
        <div class="col-sm-8 my-3">
          <%= form_with url: favorites_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Favorite Recipe",
              data: { virtual_keyboard_target: 'search', action: "click->virtual-keyboard#showKeyboard" },
              value: ""
            %>
            <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
          <% end %>
        </div>
        <div class="keyboard-container d-none" data-virtual-keyboard-target='keyboard'>
          <div class="simple-keyboard"></div>
        </div>
      </div>
    </div>
  </div>
<div class="my-4 mx-4" id="blurContainer">
  <% if @favorite_recipes.empty? %>
    <h2>Recipe not found</h2>
  <% else %>
    <% @favorite_recipes.each do |recipe| %>
      <div class="card-whole-fav mt-3" data-controller="favoritable"  data-favoritable-mark-path-value="<%= mark_path(recipe.id) %>"  data-favoritable-unmark-path-value="<%= unmark_path(recipe.id) %>" data-favoritable-like-path-value="<%= like_path(recipe.id) %>" data-favoritable-unlike-path-value="<%= unlike_path(recipe.id) %>">
        <div class="position-relative">
          <div class="col-md-4" data-bs-toggle="modal" data-bs-target="#exampleModal<%= recipe.id %>">
            <%= cl_image_tag recipe.photo.key, class:"d-block actual-pic ", alt:"Poster", crop: :fill, style:" width: 100%; height: 170px;object-fit: cover;"  %>
          </div>
          <div class="position-absolute top-0 start-0 p-2">
            <i class="fas fa-info-circle"></i>
          </div>
        </div>
        <div class="card-body">
          <h5 class="mx-2 my-2 name-recipe"><%= recipe.name.capitalize%></h5>
          <div class="mx-2 d-flex justify-content-end">
            <p class="p-icon-fav "><i class="mx-2 pe-2 fa-solid fa-user-group iconico ">   <%= recipe.number_of_portions%></i></p>
            <p class="p-icon-fav "><i class=" fa-regular fa-clock iconico ">   <%= recipe.preparation_time%></i>m</p>
          </div>
          <div class="d-flex" >
            <div class="cardib">
              <p class="cardib-text"><%= raw recipe.description.first(180)%>...</p>
            </div>
          </div>
        </div>
        <div class="mx-2 d-flex justify-content-end align-items-end">
          <i class="fa-solid fa-heart icon-index  <%= 'd-none' unless recipe.favorited_by?(current_user) %>"  data-favoritable-target="liked" style="color: #ff2600;" data-action="click->favoritable#unlike_js"></i>
          <i class="fa-regular fa-heart icon-index  <%= 'd-none' if recipe.favorited_by?(current_user) %>" data-favoritable-target="unliked"  style="color: #ff2600;" data-action="click->favoritable#like_js"></i>
        </div>
      </div>
      <%# Trying to push this part.  %>
      <!-- Modal -->
      <div class="modal fade"  id="exampleModal<%= recipe.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" style="top: -45px;">
        <div class="modal-dialog modal-dialog-centered sizing">
          <div class="modal-content radius-card " style="border-bottom-left-radius: 77px; border-bottom-right-radius: 70px;">
            <div class="modal-header modal-img-card">
              <i class=" ml-10 fa-solid fa-circle-left" style="color: #ab82b3" data-bs-dismiss="modal"></i>
              <div class="background-banner">
                <%= cl_image_tag recipe.photo.key, class:"actual-pic modal-pic ", alt:"Banner", crop: :fill  %>
              </div>
            </div>
            <div class="card card-modal-favorite">
                <div class="modal-body ">
                  <h1 class="modal-title bold-title" id="exampleModalLabel" style="color:black"><%= recipe.name.capitalize%></h1>
                  <hr style="color:black">
                  <div class="instructions">
                    <div class="cardi-instruction" style="color:black"><%= raw recipe.instruction %></div>
                  </div>
                </div>

                <div class="d-flex justify-content-space-between mt-3"  >
                  <div class="d-flex" >
                    <div class=" justify-content-center icons-clock">
                      <p><i class=" fa-solid fa-user-group " style="color:black" ><%= recipe.number_of_portions%></i></p>
                      <p><i class=" fa-regular fa-clock" style="color:black" ><%= recipe.preparation_time %></i></p>
                    </div>
                  </div>
                  <div class="done">
                    <i class="fa-solid fa-heart icon-index  <%= 'd-none' unless recipe.favorited_by?(current_user) %>"  data-favoritable-target="liked" style="color: #ff2600;" data-action="click->favoritable#unlike_js"></i>
                    <i class="fa-regular fa-heart icon-index  <%= 'd-none' if recipe.favorited_by?(current_user) %>" data-favoritable-target="unliked"  style="color: #ff2600;" data-action="click->favoritable#like_js"></i>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/index.html.erb
<div>
  <div class="text-center" >
    <h1 class="color-green-bk"> Recipes:</h1>
  </div>
  <div class="my-4 mx-4">
    <% if @recipes.empty? %>
      <h2>Recipe not found</h2>
    <% else %>
      <% @recipes.each do |recipe| %>
        <div  data-controller="favoritable"  data-favoritable-mark-path-value="<%= mark_path(recipe.id) %>"  data-favoritable-unmark-path-value="<%= unmark_path(recipe.id) %>" data-favoritable-like-path-value="<%= like_path(recipe.id) %>" data-favoritable-unlike-path-value="<%= unlike_path(recipe.id) %>">
          <div class="card-whole-index mt-3">
            <div class="position-relative">
              <div class="col-md-4" data-bs-toggle="modal" data-bs-target="#exampleModal<%= recipe.id %>">
                <%= cl_image_tag recipe.photo.key, class:"d-block actual-pic ", alt:"Poster", crop: :fill, style:" width: 100%; height: 170px;object-fit: cover;"  %>
              </div>
              <div class="position-absolute top-0 start-0 p-2">
                <i class="fas fa-info-circle"></i>
              </div>
            </div>

            <div class="card-body">
              <%# <div class="mx-2 d-flex justify-content-center"> %>
                <h5 class="mx-2 my-2 name-recipe"><%= recipe.name.capitalize%></h5>
              <%# </div> %>
              <div class="mx-2 d-flex justify-content-end">
                <p class="p-icon-fav "><i class="mx-2 pe-2 fa-solid fa-user-group iconico ">   <%= recipe.number_of_portions%></i></p>
                <p class="p-icon-fav "><i class=" fa-regular fa-clock iconico ">   <%= recipe.preparation_time%></i>m</p>
              </div>
              <div class="d-flex" >
                <div class="cardib">
                  <p class="cardib-text"><%= raw recipe.description.first(180)%>...</p>
                </div>
              </div>
            </div>

            <div class="mx-2 d-flex justify-content-end align-items-end">
              <i class="fa-regular fa-circle-check icon-index px-1 <%= 'd-none' if recipe.done? %>" <%= recipe.id %> style="color: gray " data-favoritable-target="markasdone"  data-action="click->favoritable#mark_js" ></i>
              <i class="fa-regular fa-circle-check icon-index px-1 <%= 'd-none' unless recipe.done? %>" <%= recipe.id %> style="color: green" data-favoritable-target="markedasdone"  data-action="click->favoritable#unmark_js" ></i>
            </div>
          </div>
             <!-- Modal -->
             <div class="modal fade"  id="exampleModal<%= recipe.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" style="top: -45px;">
                <div class="modal-dialog modal-dialog-centered sizing">
                  <div class="modal-content radius-card " style="border-bottom-left-radius: 77px; border-bottom-right-radius: 70px;">
                    <div class="modal-header modal-img-card">
                      <i class=" ml-10 fa-solid fa-circle-left" style="color: #719f7c" data-bs-dismiss="modal"></i>
                      <div class="background-banner">
                        <%= cl_image_tag recipe.photo.key, class:"actual-pic modal-pic ", alt:"Banner", crop: :fill  %>
                      </div>
                    </div>
                    <div class="card card-modal" style="background-color: #7eb48b;">
                        <div class="modal-body ">
                          <h1 class="modal-title bold-title" id="exampleModalLabel" style="color: black"><%= recipe.name.capitalize%></h1>
                          <hr style="color: black">
                          <div class="instructions">
                            <div class="cardi-instruction" style="color: black"><%= raw recipe.instruction %></div>
                          </div>
                        </div>
                      <div class="d-flex justify-content-space-between mt-3"  >
                        <div class="d-flex" >
                          <div class=" justify-content-center icons-clock">
                            <p><i class=" fa-solid fa-user-group " style="color: black" ><%= recipe.number_of_portions%></i></p>
                            <p><i class=" fa-regular fa-clock" style="color: black" ><%= recipe.preparation_time %></i></p>
                          </div>
                        </div>
                        <div class="done">
                          <i class="fa-regular fa-circle-check icon-index px-1 <%= 'd-none' if recipe.done? %>" <%= recipe.id %> style="color: gray " data-favoritable-target="markasdone"  data-action="click->favoritable#mark_js" ></i>
                          <i class="fa-regular fa-circle-check icon-index px-1 <%= 'd-none' unless recipe.done? %>" <%= recipe.id %> style="color: green" data-favoritable-target="markedasdone"  data-action="click->favoritable#unmark_js" ></i>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipes/index_original.html.erb
<div class="margin-bottom">
  <div class=" text-center " >
      <h1 class="color-green-bk"> Recipes:</h1>
    <div class=" my-4 div-color">
      <% if @recipes.empty? %>
        <h2>Recipe not found</h2>
      <% else %>
        <% @recipes.each do |recipe| %>
          <div  data-controller="favoritable"  data-favoritable-mark-path-value="<%= mark_path(recipe.id) %>"  data-favoritable-unmark-path-value="<%= unmark_path(recipe.id) %>" data-favoritable-like-path-value="<%= like_path(recipe.id) %>" data-favoritable-unlike-path-value="<%= unlike_path(recipe.id) %>">
            <div class="text-center">
                <div class="my-3 pb-3 actual-card border-bottom"  style="">
                  <div class="row g-0 ">
                    <div class="col-md-4 " data-bs-toggle="modal" data-bs-target="#exampleModal<%= recipe.id %>">
                      <%# <img src="..." class="img-fluid rounded-start" alt="..."> %>
                      <%= cl_image_tag recipe.photo.key, class:"d-block actual-pic ", alt:"Poster", crop: :fill, style:" width: 100%; height: 200px;object-fit: cover;"  %>
                    </div>
                    <div class="col-md-6">
                      <%# <div class="card-body"> %>
                        <h5 class="card-title mx-2 my-2 color-title"><%= recipe.name.capitalize%></h5>
                        <div class="mx-2 d-flex justify-content-center">
                          <p><i class="mx-2 pe-2 fa-solid fa-user-group border-end">   <%= recipe.number_of_portions%></i></p>
                          <p><i class="mx-2 fa-regular fa-clock">   <%= recipe.preparation_time%></i>min</p>
                        </div>

                        <div class="d-flex" >
                          <div class="cardib">
                            <p class="cardib-text"><%= raw recipe.description.first(200)%>...</p>
                          </div>
                        </div>

                        <div class="mx-2 d-flex justify-content-end align-items-end mt-3"  >
                          <i class="fa-solid fa-heart icon-index px-2 <%= 'd-none' unless recipe.favorited_by?(current_user) %>"  data-favoritable-target="liked" style="color: #ff2600;" data-action="click->favoritable#unlike_js"></i>
                          <i class="fa-regular fa-heart icon-index px-2  <%= 'd-none' if recipe.favorited_by?(current_user) %>" data-favoritable-target="unliked"  style="color: #ff2600;" data-action="click->favoritable#like_js"></i>
                        </div>
                    </div>
                  </div>
                </div>

                <!-- Modal -->
                <div class="modal fade"  id="exampleModal<%= recipe.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" style="height:95vh">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel"><%= recipe.name.capitalize%></h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <div class="col-md-4 ">
                      <%# <img src="..." class="img-fluid rounded-start" alt="..."> %>
                      <%= cl_image_tag recipe.photo.key, class:"d-block actual-pic ", alt:"Poster", crop: :fill, style:" width: 100%; height: 200px;object-fit: cover;"  %>
                    </div>
                    <div class="col-md-6">
                      <%# <div class="card-body"> %>

                        <div class="mx-2 pt-3 d-flex justify-content-center">
                          <p><i class="mx-2 pe-2 fa-solid fa-user-group border-end">   <%= recipe.number_of_portions%></i></p>
                          <p><i class="mx-2 fa-regular fa-clock">   <%= recipe.preparation_time %></i></p>
                        </div>

                        <div class="d-flex" >
                          <div class="">
                            <div class="cardi-instruction"><%= raw recipe.instruction%></div>
                          </div>
                        </div>
                        <div class="mx-2 d-flex justify-content-end align-items-end">
                          <i class="fa-solid fa-heart icon-index px-2 <%= 'd-none' unless recipe.favorited_by?(current_user) %>"  data-favoritable-target="liked" style="color: #ff2600;" data-action="click->favoritable#unlike_js"></i>
                          <i class="fa-regular fa-heart icon-index px-2  <%= 'd-none' if recipe.favorited_by?(current_user) %>" data-favoritable-target="unliked"  style="color: #ff2600;" data-action="click->favoritable#like_js"></i>
                        </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<%# Trying to send this code %>
<%# Trying to send this code 2%>

app/views/recipes/show.html.erb
<%= @recipe %>