config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated(:user) do
    root to: "fridge_lists#show", as: :authenticated_root
  end
  root to: "pages#home"

  resources :fridge_lists, only: [ :show ] do
   resources :fridge_list_ingredients, only: [:create]
  end

  resources :recipes, only: [ :index ] do
    resources :reviews, only: [:create]
  end

  resources :ingredients, only: [:destroy]
  resources :reviews, only: [:destroy]
  resources :fridge_list_ingredients, only: [:destroy]




  get "recipes/:recipe_id/like_rails", to: "recipes#like_rails", as: :like
  get "recipes/:recipe_id/unlike_rails", to: "recipes#unlike_rails", as: :unlike
  get "recipes/:recipe_id/mark", to: "recipes#mark", as: :mark
  get "recipes/:recipe_id/mark_undone", to: "recipes#mark_undone", as: :unmark
  get "recipes/all_done_recipes", to: "recipes#all_done_recipes", as: :all_done
  get "favorites", to: "recipes#all_favorite_recipes", as: :favorites
  post '/recipes', to: 'recipes#index', as: 'search_recipes'


end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div id="infoAlert" class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
  <script>
    setTimeout(function() {
      document.getElementById("infoAlert").classList.add("fade-out");
    }, 3000); // 3000 milliseconds (3 seconds) timer
  </script>
<% end %>

<% if alert %>
  <div id="warningAlert" class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
  <script>
    setTimeout(function() {
      document.getElementById("warningAlert").classList.add("fade-out");
    }, 3000); // 3000 milliseconds (3 seconds) timer
  </script>
<% end %>

app/views/shared/_footer.html.erb
<div class="px-4 footer d-flex justify-content-between ">
  <%# <a href=" /fridge_lists/:id" class=" d-flex align-items-center text-decoration-none "><i class="fa-solid fa-carrot fa-color"></i></a> %>
  <%= link_to "<i class='fa-solid fa-user fa-color'></i>".html_safe, destroy_user_session_path, class: "dropdown-item d-flex align-items-center text-decoration-none w-auto", data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to logout?' } %>
  <a href="<%= all_done_path %>" class=" d-flex align-items-center text-decoration-none "><i class="fa-regular fa-square-check <%= request.path == '/recipes/all_done_recipes' ? 'fa-red' : 'fa-black' %> "></i></a>
  <%# <img id="icon-footer"  class="" src="https://res.cloudinary.com/dclozlnfy/image/upload/v1695149130/development/Screenshot_2023-09-19_at_20.45.11_exfuez.png" alt=""> %>
  <a href=" /fridge_lists/:id"><img id="icon-footer" src="https://res.cloudinary.com/dclozlnfy/image/upload/v1695149130/development/Screenshot_2023-09-19_at_20.45.11_exfuez.png" alt="fridge logo"></a>
  <a href="<%= favorites_path %>" class=" d-flex align-items-center text-decoration-none" ><i class="fa-solid fa-heart <%= request.path == '/favorites' ? 'fa-red' : 'fa-black' %> "></i></a>
  <%# <a href="destroy_user_session_path" class=" d-flex align-items-center text-decoration-none"><i class="fa-solid fa-user fa-color"></i></a> %>
  <%#= link_to "Log out", destroy_user_session_path, class: "dropdown-item d-flex align-items-center text-decoration-none w-auto", data: {turbo_method: :delete} %>
  <%#= link_to "<i class='fa-solid fa-user fa-color'></i>".html_safe, destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>

</div>

app/views/shared/_form.html.erb
<%= simple_form_for(article) do |f| %>
  <!-- [...] -->
  <%= f.input :photo, as: :file %>
  <!-- [...] -->
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>